version: '2.1'

services:
  jenkins:
    container_name: jenkins
    image: psykosoldi3r/jenkins
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"  
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked  
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home